/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef NODES_H
#define NODES_H

/*
 * function declarations 
 */
void            init_nodes(void);
FindVarMethod   var_nodes;
FindVarMethod   var_nodeTable;

#endif                          /* NODES_H */
