/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef NODES_COLUMNS_H
#define NODES_COLUMNS_H

/*
 * column number definitions for table nodeTable 
 */
#define COLUMN_NODEINDEX		1
#define COLUMN_NODEVERSION		2
#endif                          /* NODES_COLUMNS_H */
